{...}: {
  flake.modules.nixos.laptopPackages = {pkgs, ...}: {
    environment.systemPackages = with pkgs; [
      noctalia-shell
      bibata-cursors
      foot
      nemo
      file-roller
      btop
      resources
      easyeffects
      pavucontrol
      onlyoffice-desktopeditors
      gnome-calendar
      firefox
      proton-vpn
      rustdesk
      qbittorrent-enhanced
      vlc
      mpv
      obs-studio
      gpu-screen-recorder
      kdePackages.kdenlive
      audacity
      heroic
      itch
      mangohud
      lutris
      winetricks
      gamescope
      zapzap
      libreoffice-fresh
      joplin-desktop
      discord
      equibop
      zed-editor
      zed-discord-presence
      btrfs-progs
    ];
    fonts.packages = with pkgs; [
      wineWow64Packages.fonts
      nerd-fonts.jetbrains-mono
      nerd-fonts.fira-code
      corefonts
      vista-fonts
      unifont
      cascadia-code
      fira-code
      fira-sans
      inter
      roboto-serif
      noto-fonts-color-emoji
      noto-fonts-cjk-sans
      noto-fonts-cjk-serif
    ];
  };
}
